config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  resources :users
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
  end
  resources :comments
  resource :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :author,
  class_name: :User,
  foreign_key: :user_id,
  primary_key: :id

  belongs_to :post,
  class_name: :Post,
  foreign_key: :post_id,
  primary_key: :id

  has_many :child_comments,
  class_name: :Comment,
  foreign_key: :parent_comment_id,
  primary_key: :id

  belongs_to :parent_comments,
  class_name: :Comment,
  foreign_key: :parent_comment_id,
  primary_key: :id,
  optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :subs, presence: { message: "you need 1 sub" }

  belongs_to :author,
  class_name: :User,
  foreign_key: :user_id,
  inverse_of: :posts

  has_many :comments,
  class_name: :Comment,
  foreign_key: :post_id,
  primary_key: :id

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub

  def comments_by_parent_id
    hash = Hash.new { |hash, key| hash[key] = [] }

    self.comments.includes(:author).each do |comment|
      hash[comment.parent_comment_id] << comment
    end

    hash
  end
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
  class_name: :User,
  foreign_key: :moderator_id,
  primary_key: :id,
  inverse_of: :subs

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs, source: :post
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, :password_digest, :username, presence: true

  has_many :subs,
  class_name: :Sub,
  foreign_key: :moderator_id,
  primary_key: :id,
  inverse_of: :moderator

  has_many :posts,
  inverse_of: :author

  has_many :comments,
  inverse_of: :author

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    if user.valid_password?(password)
      return user
    else
      return nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if !session[:session_token]
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    redirect_to new_session_url if !logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create]

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end


  private
  def comment_params
    params.require(:comment).permit(:post_id, :body, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, except: [:show]
  before_action :require_that_user_owns_post, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to subs_url
    else
      flash[:errors] = @post.errors.full_message
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_message
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, sub_ids: [])
  end

  def require_that_user_owns_post
    return if current_user.posts.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = ['Incorrect username or password']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, except: [:index, :show]
  before_action :require_moderator_edit, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator_edit
    if current_user.subs.find_by(id: params[:id])
      return
    else
      render json: 'Must be moderator', status: :forbidden
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<span style='padding: 15px 0;'>
  <%= comment.author.username %>: <%= link_to comment.body, comment_url(comment.id) %>
</span>

<ul style='list-style: none;'>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li style='border: 1px solid black; padding-left: 10px; padding-top: 5px;'><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1 style='font-size: 30px;'>New Comment</h1>

<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label>Body
    <input type="text" name="comment[body]">
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">

  <input type="submit" value="Create Comment!">
</form>

app/views/comments/show.html.erb
<br><br><br>
<h3>Body:</h3>
<%= @comment.body %>

<h3>Author:</h3>
<%= @comment.author.username %>

<h3>Child Comments:</h3>
<% @comment.child_comments.each do |com| %>
  <li><%= com.body %></li>
<% end %>


<br><br>
<h4>Add Comment:</h2>
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label>Body
    <input type="text" name="comment[body]">
  </label>

  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">
  <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">

  <input type="submit" value="Create Comment!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon" href="/assets/reddit.ico"/>

  <section style='float: left; position: absolute;'>
    <% if current_user %>
    <%= current_user.username %>
    <%= button_to 'Sign Out', session_url, method: :delete %>
    <% else %>
    <%= link_to 'Sign In', new_session_url %>
    <%= link_to 'Sign Up', new_user_url %>
    <% end %>
  </section>

  <title>RedditClone</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900" rel="stylesheet">
</head>

<body style='margin: auto; text-align: center; font-family: Verdana; background: #CFE4F7;'>
  <a href="/subs" ><img src="https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Reddit_logo_and_wordmark.svg/1280px-Reddit_logo_and_wordmark.svg.png" alt="" style='width: 400px; margin-top: 30px;'></a>
  <hr style='background: black; height: 2px; position: relative; top: 30px;'>
  <br><br><br>
  <% if flash[:errors] %>
  <%= flash[:errors] %>
  <% end %>


  <%= yield %>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">

  <label>Title
    <input type="text" value="<%= @post.title %>" name="post[title]">
  </label>
  <br>
  <label>Content
    <input type="text" value="<%= @post.content %>" name="post[content]">
  </label>
  <br>
  <label>URL
    <input type="text" value="<%= @post.url %>" name="post[url]">
  </label>
  <br>
    <br>
  <label style='font-size: 20px; text-decoration: underline;'>Subs:</label>
  <input type="hidden" name="post[sub_ids][]" value="">
  <br>
  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
      />
    </label>
      <br>
  <% end %>

  <input type="submit" value="Edit Post!">
</form>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label>Title
    <input type="text" value="<%= @post.title %>" name="post[title]">
  </label>

  <br>

  <label>Content
    <input type="text" value="<%= @post.content %>" name="post[content]">
  </label>
  <br>
  <label>URL
    <input type="text" value="<%= @post.url %>" name="post[url]">
  </label>
  <br>
  <br>
  <label style='font-size: 20px;'>Subs:</label>
  <input type="hidden" name="post[sub_ids][]" value="">
  <br>
  <% Sub.all.each do |sub| %>
  <label><%= sub.title %>
    <input
    type="checkbox"
    value="<%= sub.id %>"
    name="post[sub_ids][]"
    <%= "checked" if @post.sub_ids.include?(sub.id) %>
    />
  </label>
  <br>
  <% end %>
  <br>
  <input type="submit" value="Create Post!">
</form>

app/views/posts/show.html.erb
<br>
<% if current_user == @post.author %>
<%= button_to 'Edit Post', edit_post_url, method: :get  %>
<% end %>

<section style="width: 400px; margin: auto; text-align: left;">
  <h1 style='font-size: 35px; text-decoration: underline;'><%= @post.title %></h1>
  <p style='margin-top: -25px;'><%= @post.url %></p>
  <li style='font-size: 20px;'><%= @post.content %></li>
</section>
<br>

<h3>Comments:</h3>

<% @post.comments_by_parent_id[nil].each do |comment| %>
    <li style='width: 400px; margin: auto; text-align: left; border: 1px solid black; padding-left: 10px; padding-top: 5px;''>
       <%= render("comments/comment",
                  comment: comment,
                  comments_by_parent: @post.comments_by_parent_id) %>
     </li>
<% end %>

<br>
<%= link_to 'Add Comment', new_post_comment_url(@post) %>
<br><br>
<section style="width: 400px; margin: auto; text-align: left; font-size: 13px;">
  <h3>Subs:</h3>
  <% @post.subs.each do |sub| %>
  <li><%= sub.title %></li>
  <% end %>
</section>

<br>
<br>
<br>
<br>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1 style='font-weight: bold; font-size: 40px;'>Subreddits:</h1>


<% @subs.each do |sub| %>
  <span style='font-size: 30px;'><%= link_to sub.title, sub_url(sub) %></span>
  <br>
  <%= sub.description %>
  <br>
  <br>
  <br>
<% end %>



<br>
<%= button_to 'Add Post', new_post_url, method: :get %>

app/views/subs/new.html.erb
<h1 style='font-size: 30px;'>New Sub</h1>

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <label>Description
    <input type="text" name="sub[description]">
  </label>

  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <input type="submit" value="Create Sub!">
</form>

app/views/subs/show.html.erb
<h1 style='font-size: 40px;'><%= @sub.title %></h1>
<h3 style='font-weight: 400; margin-top: -10px;'><%= @sub.description %></h3>


<%= link_to 'Add Post', new_post_url %>

<br>
<br>
<br>
<h2>Posts:</h2>

<section style='margin: auto; width: 600px; text-align: left;'>
  <% @sub.posts.each do |post| %>
    <a id="upvote" href="#"><span></span></a>
        <br>
    <a id="downvote" href="#"><span></span></a>
    <span style='font-size: 20px;'><%= link_to post.title, post_url(post) %></span>
    <span style='color: gray; font-size: 12px;'>(<%= post.url %>)</span><br>
    <span style='color: gray; font-size: 12px;'><%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.author.username, user_url(post.author) %></span>

    <br>

    <spans style='font-size: 13px;'><%= post.content.slice(0, 50) %>...<br></span>
    <% if current_user == post.author %>
      <%= button_to 'Edit Post', edit_post_url, method: :get  %>
    <% end %>
  <% end %>
</section>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1 style='font-size: 40px;'>Sign Up</h1>


<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="Username">Username</label>
  <input id="Username" type="text" name="user[username]" value="">

  <label for="Password">Password</label>
  <input id="Password" type="password" name="user[password]" value="">

  <input type="submit" name="" value="Sign Up">
</form>